[package]
name = "poker_solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "poker_solver"
path = "main.rs"

[dependencies]
rustc-hash = "2.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1